---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-external-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-external
  {{ end }}
  {{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
  labels:
    cert-manager.io/solver: http01
  {{ end }}
  annotations:
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx-external"
    {{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
    cert-manager.io/enabled: "true"
    {{ end }}
spec:
  tls:
    - hosts:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        - {{ .DRONE_BUILD_NUMBER }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
        - {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
      {{ else }}
        - {{ .PRODUCTION_URL }}
      {{ end }}
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      secretName: branch-tls-external
      {{ else }}
      secretName: {{ .APP_NAME }}-external
      {{ end }}
  rules:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - host: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else }}
    - host: {{ .PRODUCTION_URL }}
    {{ end }}
      http:
        paths:
          - path: /
            backend:
              {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
              {{ else }}
              serviceName: {{ .APP_NAME }}
              {{ end }}
              servicePort: 10443
