---
apiVersion: v1
kind: ConfigMap
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-configmap-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}-configmap
  {{ end }}
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    name: {{ .APP_NAME }}
    {{ end }}
data:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  NODE_ENV: development
  {{ else }}
  NODE_ENV: production
  {{ end }}
