---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fv-branch-configmap
  namespace: {{ .KUBE_NAMESPACE }}
  labels:
    name: fv-branch-configmap
data:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  NODE_ENV: development
  {{ else }}
  NODE_ENV: production
  {{ end }}
