apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: file-vault-ingress
  {{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
  labels:
    cert-manager.io/solver: http01
  {{ end }}
  annotations:
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "200m"
    ingress.kubernetes.io/proxy-connect-timeout: "360"
    ingress.kubernetes.io/proxy-send-timeout: "360"
    ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx-external"
  {{ if not (eq .KUBE_NAMESPACE .BRANCH_ENV) }}
  cert-manager.io/enabled: "true"
  {{ end }}
spec:
  tls:
  - hosts:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    - fv-branch.{{ .BRANCH_ENV }}.homeoffice.gov.uk
    {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
    - supp-docs.prod.{{ .APP_NAME }}.homeoffice.gov.uk
    {{ end }}
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    secretName: branch-tls-external
    {{ else }}
    secretName: file-vault-cert
    {{ end }}
  rules:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  - host: fv-branch.{{ .BRANCH_ENV }}.homeoffice.gov.uk
  {{ else if eq .KUBE_NAMESPACE .PROD_ENV }}
  - host: supp-docs.prod.{{ .APP_NAME }}.homeoffice.gov.uk
  {{ end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: file-vault
          servicePort: 10443
